# Generated by Django 5.2.13 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_announcement_announcementrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='post_slug',
            field=models.CharField(blank=True, help_text="Blog post slug to announce. Renders the 'new post' email template.", max_length=200),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='resend_email_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body_html',
            field=models.TextField(blank=True, help_text='HTML override — leave blank to auto-render from post_slug.'),
        ),
    ]
