# Generated by Django 5.2.13 on 2026-05-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "email_type",
                    models.CharField(
                        db_index=True,
                        default="unspecified",
                        help_text="Dotted tag, e.g. 'transactional.verification', 'marketing.newsletter'.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "status"], name="emailing_em_created_6fa7b5_idx"
                    )
                ],
            },
        ),
    ]
