# Generated by Django 5.2.13 on 2026-04-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="e.g. 'about', 'now'", unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Nav ordering')),
                ('show_in_nav', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
    ]
